INFO 2012-08-30 09:11:55,415 engines 99 unbound method produce() must be called with EventFactory instance as first argument (got dict instance instead) 
ERROR 2012-08-30 10:12:23,382 base 215 Internal Server Error: /api/v1/event/ 
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    request.path_info)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/easter/project/urls.py", line 8, in <module>
    url(r'^api/', include('easter.urls')),
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 24, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/easter/easter/urls.py", line 7, in <module>
    from views import EventView, UserEventsView
  File "/home/toureet/project/easter/easter/views.py", line 8, in <module>
    from engines import EventPostEngine, QueryGetEngine, UserEventsEngine
  File "/home/toureet/project/easter/easter/engines.py", line 5, in <module>
    from collections import (UserHashTable, EventHandler, RegisteredEvents,
  File "/home/toureet/project/easter/easter/collections/__init__.py", line 5, in <module>
    from event_register import RegisteredEvents
  File "/home/toureet/project/easter/easter/collections/event_register.py", line 5, in <module>
    from easter.mixins.mongoable import Mongoable
  File "/home/toureet/project/easter/easter/mixins/mongoable.py", line 5, in <module>
    from easter.core.mongo import get_mongodb
  File "/home/toureet/project/easter/easter/core/mongo.py", line 7, in <module>
    import pymongo
ImportError: No module named pymongo
ERROR 2012-08-30 10:12:50,162 base 215 Internal Server Error: / 
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    request.path_info)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/easter/project/urls.py", line 8, in <module>
    url(r'^api/', include('easter.urls')),
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 24, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/easter/easter/urls.py", line 7, in <module>
    from views import EventView, UserEventsView
  File "/home/toureet/project/easter/easter/views.py", line 8, in <module>
    from engines import EventPostEngine, QueryGetEngine, UserEventsEngine
  File "/home/toureet/project/easter/easter/engines.py", line 5, in <module>
    from collections import (UserHashTable, EventHandler, RegisteredEvents,
  File "/home/toureet/project/easter/easter/collections/__init__.py", line 5, in <module>
    from event_register import RegisteredEvents
  File "/home/toureet/project/easter/easter/collections/event_register.py", line 5, in <module>
    from easter.mixins.mongoable import Mongoable
  File "/home/toureet/project/easter/easter/mixins/mongoable.py", line 5, in <module>
    from easter.core.mongo import get_mongodb
  File "/home/toureet/project/easter/easter/core/mongo.py", line 7, in <module>
    import pymongo
ImportError: No module named pymongo
ERROR 2012-08-30 10:12:50,677 base 215 Internal Server Error: /favicon.ico 
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/middleware/common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/easter/project/urls.py", line 8, in <module>
    url(r'^api/', include('easter.urls')),
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 24, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/toureet/.virtualenvs/easter/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/easter/easter/urls.py", line 7, in <module>
    from views import EventView, UserEventsView
  File "/home/toureet/project/easter/easter/views.py", line 8, in <module>
    from engines import EventPostEngine, QueryGetEngine, UserEventsEngine
  File "/home/toureet/project/easter/easter/engines.py", line 5, in <module>
    from collections import (UserHashTable, EventHandler, RegisteredEvents,
  File "/home/toureet/project/easter/easter/collections/__init__.py", line 5, in <module>
    from event_register import RegisteredEvents
  File "/home/toureet/project/easter/easter/collections/event_register.py", line 5, in <module>
    from easter.mixins.mongoable import Mongoable
  File "/home/toureet/project/easter/easter/mixins/mongoable.py", line 5, in <module>
    from easter.core.mongo import get_mongodb
  File "/home/toureet/project/easter/easter/core/mongo.py", line 7, in <module>
    import pymongo
ImportError: No module named pymongo
